name = "y-sweet-server-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"

[[migrations]]
tag = "v1"
new_classes = ["YServe"]

[env.staging]
vars.USE_HTTPS = "true"
vars.WORKERS_RS_VERSION = "0.0.11"

[env.staging.durable_objects]
bindings = [
  { name = "Y_SWEET", class_name = "YServe" }
]

[[env.staging.r2_buckets]]
binding = "Y_SWEET_DATA"
bucket_name = "y-sweet-data-staging"
preview_bucket_name = "y-sweet-data-dev"

[env.test]
vars.WORKERS_RS_VERSION = "0.0.11"

[env.test.durable_objects]
bindings = [
  { name = "Y_SWEET", class_name = "YServe" }
]

[[env.test.r2_buckets]]
binding = "Y_SWEET_DATA"
bucket_name = "y-sweet-data-staging"
preview_bucket_name = "y-sweet-data-dev"

[env.auth-test]
vars.WORKERS_RS_VERSION = "0.0.11"
vars.AUTH_KEY = "quThwCWto1e3ybRQKA1pz98fANzm+/j5+zXygEIEIBQ="

[env.auth-test.durable_objects]
bindings = [
  { name = "Y_SWEET", class_name = "YServe" }
]

[[env.auth-test.r2_buckets]]
binding = "Y_SWEET_DATA"
bucket_name = "y-sweet-data-staging"
preview_bucket_name = "y-sweet-data-dev"
